# Generated by Django 6.0.4 on 2026-04-19 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('opportunity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('total_slots', models.IntegerField(default=0)),
                ('fulfilled_slots', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Contract Data',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FulfilmentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], default='all_time', max_length=20)),
                ('source', models.CharField(choices=[('graphql', 'GraphQL API'), ('sheets', 'Google Sheets'), ('combined', 'Combined')], default='combined', max_length=20)),
                ('total_slots', models.IntegerField(default=0)),
                ('fulfilled_slots', models.IntegerField(default=0)),
                ('fulfilment_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('product_breakdown', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='OOSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('slots_contracted', models.IntegerField(default=0)),
                ('slots_fulfilled', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('raw_row', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'OOS Entry',
                'ordering': ['row_index'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='started', max_length=20)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_saved', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
